PACKAGE="openjdk-8-jdk"
VERSION="8u492-b09+opensuse1"
JAVA_HOME="/usr/lib/jvm/opensuse-8-jdk-riscv64"
OPENSUSE_BASE_URL="https://download.opensuse.org/ports/riscv/tumbleweed/repo/oss/riscv64"
RPMS=(
  "java-1_8_0-openjdk-headless-1.8.0.492-4.1.riscv64.rpm"
  "java-1_8_0-openjdk-devel-1.8.0.492-4.1.riscv64.rpm"
  "java-1_8_0-openjdk-1.8.0.492-4.1.riscv64.rpm"
)
