PACKAGE="openjdk-8-jdk"
VERSION="8u492-b09+loongnix1"
JAVA_HOME="/usr/lib/jvm/loongson-8-jdk-loong64"
TARBALL_URL="https://ftp.loongnix.cn/Java/openjdk8/loongson8.1.27-fx-jdk8u492b09-linux-loongarch64-glibc2.34.tar.gz"
