PACKAGE="openjdk-17-jdk"
VERSION="17.0.19+10+loongnix1"
JAVA_HOME="/usr/lib/jvm/loongson-17-jdk-loong64"
TARBALL_URL="https://ftp.loongnix.cn/Java/openjdk17/loongson17.18.25-fx-jdk17.0.19_10-linux-loongarch64-glibc2.34.tar.gz"
