PACKAGE="openjdk-21-jdk"
VERSION="21.0.11+10+loongnix1"
JAVA_HOME="/usr/lib/jvm/loongson-21-jdk-loong64"
TARBALL_URL="https://ftp.loongnix.cn/Java/openjdk21/loongson21.11.38-fx-jdk21.0.11_10-linux-loongarch64-glibc2.34.tar.gz"
