PACKAGE="openjdk-11-jdk"
VERSION="11.0.31+11+loongnix1"
JAVA_HOME="/usr/lib/jvm/loongson-11-jdk-loong64"
TARBALL_URL="https://ftp.loongnix.cn/Java/openjdk11/loongson11.18.27-fx-jdk11.0.31_11-linux-loongarch64-glibc2.34.tar.gz"
