#!/bin/sh
set -e

JAVA_HOME="/usr/lib/jvm/loongson-8-jdk-loong64"
PRIORITY="1081"
COMMANDS="appletviewer clhsdb extcheck hsdb idlj jar jarsigner java java-rmi.cgi javac javadoc javafxpackager javah javap javapackager jcmd jconsole jdb jdeps jfr jhat jinfo jjs jmap jps jrunscript jsadebugd jstack jstat jstatd keytool native2ascii orbd pack200 policytool rmic rmid rmiregistry schemagen serialver servertool tnameserv unpack200 wsgen wsimport xjc"

if [ "$1" = "configure" ]; then
  for command in ${COMMANDS}; do
    if [ -x "${JAVA_HOME}/bin/${command}" ]; then
      update-alternatives --install "/usr/bin/${command}" "${command}" "${JAVA_HOME}/bin/${command}" "${PRIORITY}"
    fi
  done
fi

exit 0
